### ISSUE TITLE
Bug when removing DFD configuration

### ISSUE THREAD

**Issue by melbit-michaelw** [marqeta/terraform-provider-dfd#2] opened 2018-12-07 04:38 UTC
Hi,

I haven't tested very extensively (so this could easily be a false positive), but I briefly ran up an example environment using your provider (with an exact copy of the terraform code from https://medium.marqeta.com/threat-models-at-the-speed-of-devops-e235975e7c68 ) which worked as expected and generated the same diagram. However, I then removed just the dfd terraform code, and attempted a new terraform plan which failed:

Error: Error refreshing state: 4 error(s) occurred:

* dfd_process.webserver: dfd_process.webserver: unexpected EOF
* dfd_process.client: dfd_process.client: unexpected EOF
* dfd_data_store.logs: dfd_data_store.logs: unexpected EOF
* dfd_data_store.db: dfd_data_store.db: unexpected EOF

I'm assuming this is because you don't have a mechanism to remove the objects from the state file.

**Comment by rbhitchcock** [comment] 2018-12-07 04:48
@melbit-michaelw thanks so much for reporting this issue! 

I’m afraid I don’t understand exactly what you mean by “removed just the dfd terraform code.” Could you elaborate further or perhaps provide an example?

**Comment by melbit-michaelw** [comment] 2018-12-07 04:51
Absolutely. By "dfd terraform code", I'm referring to the various dfd_ resources. 

More specifically, I have my terraform code split into several files:

provider.tf (contains the provider definitions)
main.tf (contains some AWS resources)
dfd.tf (copy and paste from the threat model example)

I did a terraform plan and then apply with those files which generated the .dot file as expected. I then removed the dfd.tf file, and re-ran the terraform plan. That gave me the errors in the original post.

**Comment by rbhitchcock** [comment] 2018-12-07 04:53
Got it, thanks! I’ll look into this and get back to you. Thanks again for reporting this issue.

**Comment by rbhitchcock** [comment] 2018-12-07 18:43
So after some digging this morning, I am pretty sure this is a race condition. I was only able to reproduce it intermittently. You may have success if you use the `-parallelism=1` flag when performing your Terraform operations. I'll get this fixed, but it might take a few days.

**Comment by rbhitchcock** [comment] 2018-12-12 16:08
Hi @melbit-michaelw,

Sorry for the delay. I needed to work out some package management / dependency issues in the process of fixing the bug you reported.

Based on my investigation, the problem you were running into was due to race conditions. According to the `go` race detector, those should all be resolved now. If you continue to have problems, please let me know. You can download the latest version (v0.0.2) of the provider from the Releases page.

I'll leave this issue open for a few days to give you time to test it out.

Thanks again

**Comment by melbit-michaelw** [comment] 2018-12-12 21:23
Hey,

Appreciate the bugfix, but unfortunately I won't be in a position to test it until next year. I'm happy for you to close it off if you are confident it's resolved, and I'll open a new one if we discover any further issues next year.

**Comment by rbhitchcock** [comment] 2018-12-12 21:28
Sounds good. I"ll close it out. Please reopen if it looks like it's not resolved.

**Closed as completed by rbhitchcock** 2018-12-12 21:28 UTC
Labels: bug
